name: personal_finance_lite
description: A lightweight personal finance tracker.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  intl: ^0.20.2
  csv: ^6.0.0
  path_provider: ^2.1.2
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.5
  lottie: ^3.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/placeholder/
    - assets/images/
    - assets/animations/